# Generated by Django 3.2.3 on 2021-06-17 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sport',
            fields=[
                ('idSport', models.IntegerField(primary_key=True, serialize=False, verbose_name='id usuario')),
                ('nameSport', models.CharField(max_length=100, verbose_name='Nombre Deporte')),
            ],
        ),
        migrations.CreateModel(
            name='ComenUsuario',
            fields=[
                ('idUser', models.CharField(max_length=70, primary_key=True, serialize=False, verbose_name='id usuario')),
                ('nombreUser', models.CharField(max_length=70, verbose_name='Nombre del usuario')),
                ('titulo', models.CharField(max_length=20, verbose_name='titulo tema')),
                ('texto', models.TextField(verbose_name='texto del tema')),
                ('correo', models.CharField(max_length=70, verbose_name='Correo del usuario')),
                ('deporte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.sport')),
            ],
        ),
    ]
