# Generated by Django 3.2.3 on 2021-06-20 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sport',
            name='idSport',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='id deporte'),
        ),
    ]
